In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd
data = pd.read_csv('E:/Data_Mining_project/data/wdi.csv')
data.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,18.001597,18.558234,19.043572,19.586457,20.192064,20.828814,21.372164,22.100884,NaN,NaN
1,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,7.096003,7.406706,7.666648,8.020952,8.403358,8.718306,9.097176,9.473374,NaN,NaN
2,Africa Eastern and Southern,AFE,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.UR.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,38.488233,38.779953,39.068462,39.445526,39.818645,40.276374,40.687817,41.211606,NaN,NaN
3,Africa Eastern and Southern,AFE,Access to electricity (% of population),EG.ELC.ACCS.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,33.922276,38.859598,40.223744,43.035073,44.390861,46.282371,48.127211,48.801258,50.668330,NaN
4,Africa Eastern and Southern,AFE,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,16.527554,24.627753,25.432092,27.061929,29.154282,31.022083,32.809138,33.783960,35.375216,NaN

In [14]:
data_collection = data.loc[((data['Indicator Name'] == 'Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990)')
                                           | (data['Indicator Name'] == 'Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e)')
                                             | (data['Indicator Name'] == 'Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)')
                                              |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Agriculture (Mt CO2e)')
                                               |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Building (Energy) (Mt CO2e)')
                                                |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Fugitive Emissions (Energy) (Mt CO2e)')
                                                 |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e)')
                                                  |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Industrial Processes (Mt CO2e)')
                                                    |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e)')
                                                     |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e)')
                                                      |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Waste (Mt CO2e)')
                                                       |(data['Indicator Code'] == 'EN.ATM.PM25.MC.M3')
                                                        |(data['Indicator Code'] == 'EN.ATM.PM25.MC.ZS')
                                                         |(data['Indicator Code'] == 'EN.ATM.PM25.MC.T1.ZS')
                                                          |(data['Indicator Code'] == 'EN.ATM.PM25.MC.T2.ZS')
                                                           |(data['Indicator Code'] == 'EN.ATM.PM25.MC.T3.ZS')
                                                            |(data['Indicator Name'] == 'Life expectancy at birth, female (years)')
                                                             |(data['Indicator Name'] == 'Life expectancy at birth, male (years)')
                                                              |(data['Indicator Name'] == 'Life expectancy at birth, total (years)')
                                                               |(data['Indicator Name'] == 'Total greenhouse gas emissions excluding LULUCF (% change from 1990)')
                                                                |(data['Indicator Name'] == 'Total greenhouse gas emissions excluding LULUCF per capita (t CO2e/capita)')
                                                                 |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e)')
                                                                  |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Industrial Processes (Energy) (Mt CO2e)')
                                                                   |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Power Industry (Energy) (Mt CO2e)')
                                                                    |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Transport (Energy) (Mt CO2e)')
                                                                     |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Waste (Energy) (Mt CO2e)')
                                                                      |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Agriculture Sector (Energy) (Mt CO2e)')
                                                                       |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Building Sector (Energy) (Mt CO2e)')
                                                                        |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Fugitive Emissions Sector (Energy) (Mt CO2e)')
                                                                         |(data['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Other Sectors of Energy Use'))]
data_collection.shape

(5586, 69)

In [15]:
# create a range from 1960 to 1989 with for loop
years = []
for year in range(1960, 1990):
    years.append(str(year))
    print(years)

data_collection = data_collection.drop(columns= years)
data_collection = data_collection.drop(['Country Code','Indicator Code', '2024'], axis=1)

['1960']
['1960', '1961']
['1960', '1961', '1962']
['1960', '1961', '1962', '1963']
['1960', '1961', '1962', '1963', '1964']
['1960', '1961', '1962', '1963', '1964', '1965']
['1960', '1961', '1962', '1963', '1964', '1965', '1966']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988']
['1960', '1961', '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970', '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988', '1989']

In [16]:
data_collection.columns

Index(['Country Name', 'Indicator Name', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023'],
      dtype='object')

In [ ]:
# data_collection.to_csv('collectied_data.csv')

## Important Indicators for Analysis
### Co2 Indicators
Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990)

Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e)

Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)
### Air Quality Index
PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)
### Life Expectancy Indicator
 Life expectancy at birth, total (years)

In [18]:
data_filteration = pd.read_csv('E:/Data_Mining_project/data/collectied_data.csv')
data_filteration.shape

(5586, 37)

In [20]:
data_filteration = data_filteration.loc[(data_filteration['Indicator Name'] == 'Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e)')
                                                         |(data_filteration['Indicator Name'] == 'Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita)')
                                                         |(data_filteration['Indicator Name'] == 'PM2.5 air pollution, mean annual exposure (micrograms per cubic meter)')
                                                         |(data_filteration['Indicator Name'] == 'Total greenhouse gas emissions excluding LULUCF (% change from 1990)')
                                                         |(data_filteration['Indicator Name'] == 'Total greenhouse gas emissions excluding LULUCF per capita (t CO2e/capita)')
                                                         |(data_filteration['Indicator Name'] == 'Life expectancy at birth, total (years)')
                                                         |( data_filteration['Indicator Name'] == 'Carbon dioxide (CO2) emissions from Industrial Combustion (Energy) (Mt CO2e)')]
data_filteration.drop(columns=['Unnamed: 0'], inplace=True)
data_filteration.columns

Index(['Country Name', 'Indicator Name', '1990', '1991', '1992', '1993',
       '1994', '1995', '1996', '1997', '1998', '1999', '2000', '2001', '2002',
       '2003', '2004', '2005', '2006', '2007', '2008', '2009', '2010', '2011',
       '2012', '2013', '2014', '2015', '2016', '2017', '2018', '2019', '2020',
       '2021', '2022', '2023'],
      dtype='object')

In [21]:
data_filteration

,Country Name,Indicator Name,1990,1991,1992,1993,1994,1995,1996,1997,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
1,Africa Eastern and Southern,Carbon dioxide (CO2) emissions (total) excludi...,378.504400,370.704200,364.366500,364.464100,372.785400,392.550300,407.217700,423.815000,...,635.629700,621.866500,628.536500,637.906800,645.836700,654.540100,578.052000,606.394500,588.433500,579.865500
2,Africa Eastern and Southern,Carbon dioxide (CO2) emissions excluding LULUC...,1.232869,1.174578,1.123988,1.093279,1.088836,1.117248,1.128710,1.145022,...,1.096416,1.043373,1.026116,1.012873,0.997157,0.983492,0.845417,0.863533,0.816361,0.784641
6,Africa Eastern and Southern,Carbon dioxide (CO2) emissions from Industrial...,68.454200,62.596000,56.091800,48.104600,47.817800,48.850600,53.024300,56.873200,...,73.882500,71.218200,72.223400,68.464800,77.746100,75.661000,69.492000,74.016300,73.631100,74.899300
13,Africa Eastern and Southern,"Life expectancy at birth, total (years)",51.096326,50.873244,50.715946,51.073762,50.966589,51.482057,51.353190,51.570887,...,61.251436,61.713031,62.167981,62.591275,63.330691,63.857261,63.766484,62.979999,64.487020,65.146291
14,Africa Eastern and Southern,"PM2.5 air pollution, mean annual exposure (mic...",25.111399,24.547886,24.155248,23.906832,23.753597,23.721569,24.058755,24.788241,...,27.779344,29.515468,28.877274,27.311377,27.404295,26.248200,26.755686,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5571,Zimbabwe,Carbon dioxide (CO2) emissions from Industrial...,4.741700,4.989300,4.602800,3.864600,2.395700,2.629300,2.503600,2.282500,...,1.042500,1.094700,1.240000,1.237800,1.542000,1.611800,1.399300,1.581000,1.646300,1.781200
5578,Zimbabwe,"Life expectancy at birth, total (years)",58.319000,57.037000,55.602000,53.976000,52.537000,51.144000,48.981000,48.536000,...,58.106000,58.989000,59.760000,60.263000,60.906000,61.060000,61.530000,60.135000,62.360000,62.775000
5579,Zimbabwe,"PM2.5 air pollution, mean annual exposure (mic...",20.805737,20.379047,20.024639,19.755430,19.584340,19.524286,19.592426,19.758616,...,23.429253,23.103879,22.570698,17.997754,19.112099,18.528607,19.494180,NaN,NaN,NaN
5584,Zimbabwe,Total greenhouse gas emissions excluding LULUC...,NaN,-0.079189,2.626063,-10.494643,-13.065972,-13.425818,-9.297193,-12.156457,...,-15.211948,-12.060964,-17.297950,-18.811867,-12.927973,-17.405963,-22.060673,-15.924071,-13.166997,-9.691103
5585,Zimbabwe,Total greenhouse gas emissions excluding LULUC...,3.388285,3.298549,3.293561,2.830800,2.746224,2.709575,2.792041,2.653734,...,2.049853,2.097734,1.945612,1.882635,1.989264,1.857686,1.724145,1.828070,1.856077,1.898270

In [22]:
# imputing the missing values with mean value
data_imputed = data_filteration.copy()
data_imputed.iloc[:, 2:] = data_imputed.iloc[:, 2:].apply(lambda x: x.fillna(x.mean()), axis=1)
data_imputed = data_imputed.dropna(subset=data_imputed.columns[2:],how='all')
data_imputed.shape

(1758, 36)

In [23]:
data_imputed.head()

,Country Name,Indicator Name,1990,1991,1992,1993,1994,1995,1996,1997,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
1,Africa Eastern and Southern,Carbon dioxide (CO2) emissions (total) excludi...,378.504400,370.704200,364.366500,364.464100,372.785400,392.550300,407.217700,423.815000,...,635.629700,621.866500,628.536500,637.906800,645.836700,654.540100,578.052000,606.394500,588.433500,579.865500
2,Africa Eastern and Southern,Carbon dioxide (CO2) emissions excluding LULUC...,1.232869,1.174578,1.123988,1.093279,1.088836,1.117248,1.128710,1.145022,...,1.096416,1.043373,1.026116,1.012873,0.997157,0.983492,0.845417,0.863533,0.816361,0.784641
6,Africa Eastern and Southern,Carbon dioxide (CO2) emissions from Industrial...,68.454200,62.596000,56.091800,48.104600,47.817800,48.850600,53.024300,56.873200,...,73.882500,71.218200,72.223400,68.464800,77.746100,75.661000,69.492000,74.016300,73.631100,74.899300
13,Africa Eastern and Southern,"Life expectancy at birth, total (years)",51.096326,50.873244,50.715946,51.073762,50.966589,51.482057,51.353190,51.570887,...,61.251436,61.713031,62.167981,62.591275,63.330691,63.857261,63.766484,62.979999,64.487020,65.146291
14,Africa Eastern and Southern,"PM2.5 air pollution, mean annual exposure (mic...",25.111399,24.547886,24.155248,23.906832,23.753597,23.721569,24.058755,24.788241,...,27.779344,29.515468,28.877274,27.311377,27.404295,26.248200,26.755686,26.612640,26.612640,26.612640

In [ ]:
# data_imputed.to_csv('final_data.csv' , index=False)