In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

In [2]:
temp = pd.read_csv('E:/Data_Mining_project/data/temperature_data.csv')
temp.head()

,Country Name,Indicator Name,1990,1991,1992,1993,1994,1995,1996,1997,...,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023
0,Aruba (Neth.),Average surface temperature change (°C),33.27,33.80,33.46,33.74,33.53,33.77,32.97,33.27,...,34.44,34.20,34.44,34.10,33.70,34.17,34.10,33.60,33.27,34.43
1,Afghanistan,Average surface temperature change (°C),32.45,31.94,31.15,31.51,32.27,32.58,31.65,32.30,...,33.03,32.73,33.04,33.16,33.16,32.89,32.48,33.29,32.47,33.16
2,Angola,Average surface temperature change (°C),27.73,27.60,27.35,27.41,27.34,27.54,27.50,27.90,...,27.33,27.42,27.54,27.92,27.59,27.58,27.55,27.75,27.51,27.29
3,Anguilla (U.K.),Average surface temperature change (°C),32.07,31.94,31.74,31.93,31.94,32.17,31.50,32.07,...,32.07,32.17,32.27,32.10,31.90,32.44,32.37,31.94,31.74,32.94
4,ALA,Average surface temperature change (°C),18.08,17.87,19.41,16.33,19.78,18.95,18.27,20.87,...,19.80,18.46,18.69,17.83,21.21,19.77,19.38,20.46,20.23,19.24

In [3]:
# melt temp except country name and indicator name
cols_to_melt = [col for col in temp.columns if col not in ['Country Name', 'Indicator Name']]
temp = pd.melt(temp,
                id_vars=['Country Name','Indicator Name'],
                value_vars=cols_to_melt,
                var_name='Year',
                value_name='Temperature')
temp.head()

      Country Name                           Indicator Name  Year  Temperature
0    Aruba (Neth.)  Average surface temperature change (°C)  1990        33.27
1      Afghanistan  Average surface temperature change (°C)  1990        32.45
2           Angola  Average surface temperature change (°C)  1990        27.73
3  Anguilla (U.K.)  Average surface temperature change (°C)  1990        32.07
4              ALA  Average surface temperature change (°C)  1990        18.08

In [4]:
temp.columns

Index(['Country Name', 'Indicator Name', 'Year', 'Temperature'], dtype='object')

In [ ]:
regional_temp = temp.groupby(['Indicator Name', 'Year'])['Temperature'].mean().reset_index()
regional_temp['Year'] = regional_temp['Year'].astype(int)
fig = px.line(regional_temp, x='Year', y='Temperature', color='Indicator Name',
              title='Average Temperature of World in Degrees Celsius')
fig.update_traces(line=dict(width=3), marker=dict(size=8))
fig.update_layout(legend_title_text = 'Region', plot_bgcolor='white')
fig.show()

In [6]:
# plot regional plots with plotly line
# top 20 countries with highest average temperature
top_countries = temp.groupby('Country Name')['Temperature'].mean().sort_values(ascending=False).head(20).index
temp_top = temp[temp['Country Name'].isin(top_countries)].copy()
temp_top['Year'] = temp_top['Year'].astype(int)
fig = px.line(temp_top, x='Year', y='Temperature', color='Country Name', title='Average Temperature by Country')
fig.show()

In [7]:
# south asia plot with plotly for each country in south asia
countries = ['India', 'Pakistan', 'Bangladesh', 'Srilanka', 'Afghanistan'] 
south_asia = temp[temp['Country Name'].isin(countries)].copy()
south_asia['Year'] = south_asia['Year'].astype(int)
fig = px.line(south_asia, x='Year', y='Temperature', color='Country Name', title='Average Temperature in South Asia')
fig.show()